#include "/nix/store/26v238sdw2c5vrkjmip1xp4bm1632f7a-ghc-9.8.4/lib/ghc-9.8.4/lib/template-hsc.h"
#line 10 "FFI.hsc"
#include <liburing.h>
#line 11 "FFI.hsc"
#include <fcntl.h>
#line 12 "FFI.hsc"
#include <sys/socket.h>
#line 13 "FFI.hsc"
#include <sys/types.h>
#line 14 "FFI.hsc"
#include <netinet/in.h>

int main (void)
{
    hsc_line (1, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("", hsc_stdout());
    hsc_fputs ("-- This file is autogenerated from FFI.hsc\n"
           "", hsc_stdout());
    hsc_fputs ("-- FFI bindings to liburing using hsc2hs\n"
           "{-# LANGUAGE CApiFFI #-}\n"
           "{-# LANGUAGE MagicHash #-}  \n"
           "{-# LANGUAGE UnliftedFFITypes #-}\n"
           "{-# OPTIONS_GHC -Wall #-}\n"
           "\n"
           "module System.IoUring.Internal.FFI where\n"
           "\n"
           "", hsc_stdout());
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_fputs ("", hsc_stdout());
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_fputs ("", hsc_stdout());
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_fputs ("", hsc_stdout());
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_fputs ("", hsc_stdout());
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_fputs ("\n"
           "import Foreign\n"
           "import Foreign.C\n"
           "import GHC.Exts\n"
           "import Data.Bits (shiftL)\n"
           "import System.Posix.Types\n"
           "\n"
           "data {-# CTYPE \"struct io_uring\" #-} IoUring = IoUring\n"
           "newtype IoUringPtr = IoUringPtr (Ptr IoUring)\n"
           "\n"
           "data {-# CTYPE \"struct io_uring_params\" #-} IoUringParams = IoUringParams {\n"
           "    paramSqEntries   :: Word32,\n"
           "    paramCqEntries   :: Word32,\n"
           "    paramFlags       :: Word32,\n"
           "    paramSqThreadCpu :: Word32,\n"
           "    paramSqThreadIdle :: Word32\n"
           "  }\n"
           "\n"
           "instance Storable IoUringParams where\n"
           "  sizeOf _ = ", hsc_stdout());
#line 34 "FFI.hsc"
    hsc_size (struct io_uring_params);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (35, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("  alignment _ = ", hsc_stdout());
#line 35 "FFI.hsc"
    hsc_alignment (struct io_uring_params);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (36, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("  peek ptr = do\n"
           "    sqe <- ", hsc_stdout());
#line 37 "FFI.hsc"
    hsc_peek (struct io_uring_params, sq_entries);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr\n"
           "", hsc_stdout());
    hsc_line (38, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    cqe <- ", hsc_stdout());
#line 38 "FFI.hsc"
    hsc_peek (struct io_uring_params, cq_entries);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr\n"
           "", hsc_stdout());
    hsc_line (39, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    fl  <- ", hsc_stdout());
#line 39 "FFI.hsc"
    hsc_peek (struct io_uring_params, flags);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr\n"
           "", hsc_stdout());
    hsc_line (40, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    cpu <- ", hsc_stdout());
#line 40 "FFI.hsc"
    hsc_peek (struct io_uring_params, sq_thread_cpu);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr\n"
           "", hsc_stdout());
    hsc_line (41, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    idl <- ", hsc_stdout());
#line 41 "FFI.hsc"
    hsc_peek (struct io_uring_params, sq_thread_idle);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr\n"
           "", hsc_stdout());
    hsc_line (42, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    return (IoUringParams sqe cqe fl cpu idl)\n"
           "  poke ptr (IoUringParams sqe cqe fl cpu idl) = do\n"
           "    ", hsc_stdout());
#line 44 "FFI.hsc"
    hsc_poke (struct io_uring_params, sq_entries);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr sqe\n"
           "", hsc_stdout());
    hsc_line (45, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    ", hsc_stdout());
#line 45 "FFI.hsc"
    hsc_poke (struct io_uring_params, cq_entries);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr cqe\n"
           "", hsc_stdout());
    hsc_line (46, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    ", hsc_stdout());
#line 46 "FFI.hsc"
    hsc_poke (struct io_uring_params, flags);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr fl\n"
           "", hsc_stdout());
    hsc_line (47, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    ", hsc_stdout());
#line 47 "FFI.hsc"
    hsc_poke (struct io_uring_params, sq_thread_cpu);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr cpu\n"
           "", hsc_stdout());
    hsc_line (48, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("    ", hsc_stdout());
#line 48 "FFI.hsc"
    hsc_poke (struct io_uring_params, sq_thread_idle);
    hsc_fputs (" ", hsc_stdout());
    hsc_fputs ("ptr idl\n"
           "", hsc_stdout());
    hsc_line (49, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("\n"
           "data IoSqeFlag = IosqeFixedFile\n"
           "               | IosqeIoDrain\n"
           "               | IosqeIoLink\n"
           "               | IosqeAsync\n"
           "               | IosqeBufferSelect\n"
           "               deriving (Show, Eq)\n"
           "\n"
           "iosqeFixedFile    :: Word8\n"
           "iosqeFixedFile    = ", hsc_stdout());
#line 58 "FFI.hsc"
    hsc_const (IOSQE_FIXED_FILE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (59, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("iosqeIoDrain      :: Word8\n"
           "iosqeIoDrain      = ", hsc_stdout());
#line 60 "FFI.hsc"
    hsc_const (IOSQE_IO_DRAIN);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (61, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("iosqeIoLink       :: Word8\n"
           "iosqeIoLink       = ", hsc_stdout());
#line 62 "FFI.hsc"
    hsc_const (IOSQE_IO_LINK);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (63, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("iosqeAsync        :: Word8\n"
           "iosqeAsync        = ", hsc_stdout());
#line 64 "FFI.hsc"
    hsc_const (IOSQE_ASYNC);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (65, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("iosqeBufferSelect :: Word8\n"
           "iosqeBufferSelect = ", hsc_stdout());
#line 66 "FFI.hsc"
    hsc_const (IOSQE_BUFFER_SELECT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (67, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("\n"
           "data {-# CTYPE \"struct io_uring_sqe\" #-} IoUringSqe = IoUringSqe\n"
           "\n"
           "data OpCode\n"
           "  = OpNop | OpReadv | OpWritev | OpFsync | OpReadFixed | OpWriteFixed\n"
           "  | OpPollAdd | OpPollRemove | OpSyncFileRange | OpSendMsg | OpRecvMsg\n"
           "  | OpTimeout | OpTimeoutRemove | OpAccept | OpAsyncCancel | OpLinkTimeout\n"
           "  | OpConnect | OpFallocate | OpOpenat2 | OpStatx | OpFadvise | OpMadvise\n"
           "  | OpSend | OpRecv | OpOpenat | OpClose | OpFilesUpdate | OpStatx\n"
           "  | OpRead | OpWrite | OpFtruncate | OpZcSend | OpZcSendMsg\n"
           "  | OpZcRecv | OpZcRecvMsg\n"
           "  deriving (Show, Eq, Enum, Bounded)\n"
           "\n"
           "opcode :: OpCode -> Word8\n"
           "opcode OpNop   = ", hsc_stdout());
#line 81 "FFI.hsc"
    hsc_const (IORING_OP_NOP);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (82, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpReadv = ", hsc_stdout());
#line 82 "FFI.hsc"
    hsc_const (IORING_OP_READV);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (83, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpWritev = ", hsc_stdout());
#line 83 "FFI.hsc"
    hsc_const (IORING_OP_WRITEV);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (84, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpFsync = ", hsc_stdout());
#line 84 "FFI.hsc"
    hsc_const (IORING_OP_FSYNC);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (85, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpReadFixed = ", hsc_stdout());
#line 85 "FFI.hsc"
    hsc_const (IORING_OP_READ_FIXED);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (86, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpWriteFixed = ", hsc_stdout());
#line 86 "FFI.hsc"
    hsc_const (IORING_OP_WRITE_FIXED);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (87, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpPollAdd = ", hsc_stdout());
#line 87 "FFI.hsc"
    hsc_const (IORING_OP_POLL_ADD);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (88, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpPollRemove = ", hsc_stdout());
#line 88 "FFI.hsc"
    hsc_const (IORING_OP_POLL_REMOVE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (89, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpSyncFileRange = ", hsc_stdout());
#line 89 "FFI.hsc"
    hsc_const (IORING_OP_SYNC_FILE_RANGE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (90, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpSendMsg = ", hsc_stdout());
#line 90 "FFI.hsc"
    hsc_const (IORING_OP_SENDMSG);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (91, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpRecvMsg = ", hsc_stdout());
#line 91 "FFI.hsc"
    hsc_const (IORING_OP_RECVMSG);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (92, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpTimeout = ", hsc_stdout());
#line 92 "FFI.hsc"
    hsc_const (IORING_OP_TIMEOUT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (93, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpTimeoutRemove = ", hsc_stdout());
#line 93 "FFI.hsc"
    hsc_const (IORING_OP_TIMEOUT_REMOVE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (94, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpAccept = ", hsc_stdout());
#line 94 "FFI.hsc"
    hsc_const (IORING_OP_ACCEPT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (95, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpAsyncCancel = ", hsc_stdout());
#line 95 "FFI.hsc"
    hsc_const (IORING_OP_ASYNC_CANCEL);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (96, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpLinkTimeout = ", hsc_stdout());
#line 96 "FFI.hsc"
    hsc_const (IORING_OP_LINK_TIMEOUT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (97, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpConnect = ", hsc_stdout());
#line 97 "FFI.hsc"
    hsc_const (IORING_OP_CONNECT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (98, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpFallocate = ", hsc_stdout());
#line 98 "FFI.hsc"
    hsc_const (IORING_OP_FALLOCATE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (99, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpOpenat2 = ", hsc_stdout());
#line 99 "FFI.hsc"
    hsc_const (IORING_OP_OPENAT2);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (100, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpStatx = ", hsc_stdout());
#line 100 "FFI.hsc"
    hsc_const (IORING_OP_STATX);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (101, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpFadvise = ", hsc_stdout());
#line 101 "FFI.hsc"
    hsc_const (IORING_OP_FADVISE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (102, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpMadvise = ", hsc_stdout());
#line 102 "FFI.hsc"
    hsc_const (IORING_OP_MADVISE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (103, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpSend = ", hsc_stdout());
#line 103 "FFI.hsc"
    hsc_const (IORING_OP_SEND);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (104, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpRecv = ", hsc_stdout());
#line 104 "FFI.hsc"
    hsc_const (IORING_OP_RECV);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (105, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpOpenat = ", hsc_stdout());
#line 105 "FFI.hsc"
    hsc_const (IORING_OP_OPENAT);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (106, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpClose = ", hsc_stdout());
#line 106 "FFI.hsc"
    hsc_const (IORING_OP_CLOSE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (107, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpFilesUpdate = ", hsc_stdout());
#line 107 "FFI.hsc"
    hsc_const (IORING_OP_FILES_UPDATE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (108, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpStatx = ", hsc_stdout());
#line 108 "FFI.hsc"
    hsc_const (IORING_OP_STATX);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (109, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpRead = ", hsc_stdout());
#line 109 "FFI.hsc"
    hsc_const (IORING_OP_READ);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (110, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpWrite = ", hsc_stdout());
#line 110 "FFI.hsc"
    hsc_const (IORING_OP_WRITE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (111, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpFtruncate = ", hsc_stdout());
#line 111 "FFI.hsc"
    hsc_const (IORING_OP_FTRUNCATE);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (112, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpZcSend = ", hsc_stdout());
#line 112 "FFI.hsc"
    hsc_const (IORING_OP_ZC_SEND);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (113, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpZcSendMsg = ", hsc_stdout());
#line 113 "FFI.hsc"
    hsc_const (IORING_OP_ZC_SENDMSG);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (114, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpZcRecv = ", hsc_stdout());
#line 114 "FFI.hsc"
    hsc_const (IORING_OP_ZC_RECV);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (115, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("opcode OpZcRecvMsg = ", hsc_stdout());
#line 115 "FFI.hsc"
    hsc_const (IORING_OP_ZC_RECVMSG);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (116, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("\n"
           "foreign import ccall unsafe \"io_uring_queue_init\"\n"
           "  c_io_uring_queue_init :: CInt -> Ptr IoUring -> Word32 -> IO CInt\n"
           "\n"
           "foreign import ccall unsafe \"io_uring_queue_enter\"\n"
           "  c_io_uring_queue_enter :: Ptr IoUring -> Word32 -> Word32 -> Word32 -> Ptr StructSigset -> CSize -> IO CInt\n"
           "\n"
           "foreign import ccall unsafe \"io_uring_get_sqe\"\n"
           "  c_io_uring_get_sqe :: Ptr IoUring -> IO (Ptr IoUringSqe)\n"
           "\n"
           "foreign import ccall unsafe \"io_uring_submit\"\n"
           "  c_io_uring_submit :: Ptr IoUring -> IO CInt\n"
           "\n"
           "foreign import ccall unsafe \"io_uring_submit_and_wait\"\n"
           "  c_io_uring_submit_and_wait :: Ptr IoUring -> Word32 -> IO CInt\n"
           "\n"
           "foreign import ccall \"&io_uring_queue_exit\"\n"
           "  c_io_uring_queue_exit :: FinalizerPtr IoUring\n"
           "\n"
           "data {-# CTYPE \"struct io_timespec\" #-} IoTimespec = IoTimespec {\n"
           "    timespecSec  :: CLong,\n"
           "    timespecNsec :: CLong\n"
           "  }\n"
           "\n"
           "instance Storable IoTimespec where\n"
           "  sizeOf _ = ", hsc_stdout());
#line 141 "FFI.hsc"
    hsc_size (struct __kernel_timespec);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (142, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("  alignment _ = ", hsc_stdout());
#line 142 "FFI.hsc"
    hsc_alignment (struct __kernel_timespec);
    hsc_fputs ("\n"
           "", hsc_stdout());
    hsc_line (143, "src/System/IoUring/Internal/FFI.hsc");
    hsc_fputs ("\n"
           "-- Additional socket-related constants\n"
           "", hsc_stdout());
#line 145 "FFI.hsc"
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_CONFIRM "),  MSG_CONFIRM);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_DONTROUTE "),  MSG_DONTROUTE);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_EOR "),  MSG_EOR);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_MORE "),  MSG_MORE);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_NOSIGNAL "),  MSG_NOSIGNAL);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_OOB "),  MSG_OOB);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_CMSG_CLOEXEC "),  MSG_CMSG_CLOEXEC);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_DONTWAIT "),  MSG_DONTWAIT);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_ERRQUEUE "),  MSG_ERRQUEUE);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_PEEK "),  MSG_PEEK);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_TRUNC "),  MSG_TRUNC);
    hsc_enum (MsgFlag,  MsgFlag, hsc_printf ("%s", "MSG_WAITALL "),  MSG_WAITALL);
    return 0;
}
